### ISSUE TITLE
getting TMPDIR from environment breaks fixture testing

### ISSUE THREAD

**Issue by stevekm** [mskcc/beagle#106]
Part of `construct_roslin_pair.py` retrieves the tmp dir from environment variable:

https://github.com/mskcc/beagle/blob/f4f019970af75c48385d79b8c750e0f35890d6df/runner/operator/roslin_operator/construct_roslin_pair.py#L156

However this breaks testing against saved fixtures because the `TMPDIR` variable on e.g. Linux is not the same as on macOS when testing, resulting in failed test.

**Comment by allanbolipata** [comment]
What is the failed test? It definitely should be set differently, but this was carried over from what's used by legacy ROSLIN, here: https://github.com/mskcc/roslin-variant/blob/2.6.x/setup/bin/roslin_request_to_yaml.py#L444-L447

When you have time, since you are most familiar with the test, I will probably suggest that you fix this (but don't do anything with it yet, I'm sure your plate is currently full)

**Comment by stevekm** [comment]
In the `test-roslin` branch,  test [`test_construct_roslin_jobs1`](https://github.com/mskcc/beagle/blob/ad1c1aed01832f1f3ebff65ca8d98fb952145601/runner/tests/operator/roslin_operator/test_construct_roslin_pair.py#L58) will fail if `TMPDIR` is set on macOS;

```
======================================================================
FAIL: test_construct_roslin_jobs1 (runner.tests.operator.roslin_operator.test_construct_roslin_pair.TestConstructPair)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kellys5/projects/beagle-dev/beagle-dev2/runner/tests/operator/roslin_operator/test_construct_roslin_pair.py", line 59, in test_construct_roslin_jobs1
    self.assertTrue(roslin_inputs == expected_inputs)
AssertionError: False is not true
```

This is because the `tmp_dir` value is hard-coded into the static saved fixture, which represents Roslin jobs that were generated on Juno;

https://github.com/mskcc/beagle/blob/test-roslin/fixtures/tests/10075_D_single_TN_pair.roslin.input.json#L344

```
            "tmp_dir": "/scratch",
```

`/scratch` was the `TMPDIR` value on Juno.

This fixture is used to validate that Roslin jobs are being created correctly. However the dynamic nature of the value for `tmp_dir` invalidates the fixture when running on another system. 

Since you need some kind of static known base-case to validate that jobs look exactly correct, but the jobs themselves are generated dynamically in this fasion, I am not sure what the ideal solution would be. 

In practice I have just been getting around it by unsetting `TMPDIR` when running tests; 

https://github.com/mskcc/beagle/blob/test-roslin/Makefile#L319

**Comment by allanbolipata** [comment]
This is solved, but we need to remove this from the operator logic for future use
