### ISSUE TITLE
need a database File validator

### ISSUE THREAD

**Issue by stevekm** [mskcc/beagle#111]
It might be a good idea to have a script/function/method/etc. to run periodically in order to validate that File entries in the database are still valid and exist in the filesystem. Maybe a weekly celery-beat task or similar? Or maybe a method to include in operators that use File that check's for file's existence in the filesystem before using a given File in a pipeline input.

possibly something simple like this:

```
class File(BaseModel):
    path = models.CharField(max_length=1500, unique=True)
    ...

    def exists(self):
        return(os.path.exists(self.path))
``` 

```
# check for files that no longer exist

all_files = File.objects.all()
for item in all_files:
    if not item.exists():
        yield(item)
```

**Comment by allanbolipata** [comment]
For the archived fastq files, right now we are guaranteed that the file paths will not be moved, based on policies they've discussed. We also have guarantees that if they WERE to be moved, they will inform us so we can plan a migration.

As for output files we've generated, we definitely should have something like this but when we brought it up in the pipeline meeting - and before Voyager project start - we were told they don't care if the files get moved or deleted so long as we can reproduce making the file. 

Something like this feature would be nice but it shouldn't be added any time soon.

**Comment by stevekm** [comment]
We have already run into cases where File and/or FileMetadata entries in the database no longer exist on the filesystem. This has caused problems with some previous database migrations. Since the database does not enforce file existence on its own, it seems inevitable that the filesystem will eventually become inconsistent with the File/FileMetadata entries in the db and start breaking things again. With a file validator, we could at least have a way to detect this ahead of time and handle it somehow.

**Comment by stevekm** [comment]
probably more useful to just have a script that can be ran independently as-needed to check for this, instead of building it into the server system's behavior. It seems like most failures that would result from this would be happening outside the direct scope of Beagle, such as within the pipeline itself.
