### ISSUE TITLE
need ability to override the output directory for pipelines

### ISSUE THREAD

**Issue by stevekm** [mskcc/beagle#112]
Right now, the output directory for pipelines in Beagle are hard-coded in the database. I believe this makes it impossible to test-run the current pipelines without outputting results to the production output location. Similarly, its not possible to test development of a new pipeline without hard-coding in the output directory path. 

I think it would be helpful to give a relative path for pipeline output directory locations, and set the output directory root path in the Django settings via environment variable or similar. This way, production pipeline database fixtures and newly developed pipelines can be run in a test environment without polluting the production directory.

# Current implementation

- pipeline fixture in database:

```
{
        "model": "runner.pipeline",
        "pk": "cb5d793b-e650-4b7d-bfcd-882858e29cc5",
        "fields": {
            "output_directory": "/juno/work/pi/beagle/output/roslin_pair_sv"
        }
    },
```

# Suggested implementation

- pipeline fixture in database:

```
{
        "model": "runner.pipeline",
        "pk": "cb5d793b-e650-4b7d-bfcd-882858e29cc5",
        "fields": {
            "output_directory": "roslin_pair_sv"
        }
    },
```

- `beagle/settings.py`:

```
OUTPUT_DIR = os.environ.get('BEAGLE_OUTPUT_DIR', '/juno/work/pi/beagle/output')
```

output directory for Roslin pipeline would be resolved to `/juno/work/pi/beagle/output/roslin_pair_sv`

**Comment by allanbolipata** [comment]
> Right now, the output directory for pipelines in Beagle are hard-coded in the database.

They are not actually hard-coded - they are set when the pipeline is registered into beagle. See the Django administration page below:

![image](https://user-images.githubusercontent.com/33229763/73404887-950c8080-42c0-11ea-9366-1fc0c565e031.png)

When the pipeline is registered, we set the absolute path, which gives us more flexibility than the suggestion here, which would've required setting an environmental variable. Through the Django administration page, it is also possible to change the output path.

> This way, production pipeline database fixtures and newly developed pipelines can be run in a test environment without polluting the production directory.

You can register newly developed pipelines and set a different output path for them in whatever test environment. It can be set at runtime and then also changed, if preferred.

I am closing this as I think it is unnecessary, but feel free to re-open or ask me directly if you have any questions. I'm always happy to take questions!

**Comment by allanbolipata** [comment]
Spoke too soon - after speaking with @stevekm, I think this might be worth revisiting. Let's discuss!

**Comment by stevekm** [comment]
this is currently implemented with the `demo-run` methods in the Makefile referenced here; https://github.com/mskcc/beagle/issues/131

by just creating a new pipeline entry with the desired output location
