### ISSUE TITLE
Create a Docker container for building Singularity images for Beagle and Ridgeback

### ISSUE THREAD

**Issue by allanbolipata** [mskcc/beagle#118]
Create a Docker container for building Singularity images for Beagle and Ridgeback, and document steps for that.

**Comment by stevekm** [comment]
There is an example of a Dockerfile for running Singularity version 2.5.2 here: https://github.com/NYU-Molecular-Pathology/containers/blob/9e81db47b1013eeefab50af34811bc7749ba4b9c/Singularity-2.5.2/Dockerfile

Hopefully more recent versions of Sigularity will not be much more complicated.

An example scripted Singularity container build method inside this Docker container can be found here: 

https://github.com/NYU-Molecular-Pathology/containers/blob/9e81db47b1013eeefab50af34811bc7749ba4b9c/Makefile#L82-L93

these can be used as templates for this task

**Comment by stevekm** [comment]
also do we have a list of what things we are building Singularity images for? Is this for Beagle/Ridgeback services?

**Comment by allanbolipata** [comment]
Cool! Need to build these https://github.com/mskcc/beagle/tree/master/container
and these
https://github.com/mskcc/ridgeback/tree/master/container

We currently use `singularity/3.5.x` to build.

**Comment by stevekm** [comment]
this was implemented here for Ridgeback: https://github.com/mskcc/ridgeback/pull/44

the same methods would be used for Beagle

**Comment by allanbolipata** [comment]
@stevekm has this been done for Beagle?

**Comment by allanbolipata** [comment]
This should be done.
