### ISSUE TITLE
Need 'assay' included in Run output_metadata

### ISSUE THREAD

**Issue by stevekm** [mskcc/beagle#121]
In order to make the assay type accessible to downstream piplelines, the "assay" metadata value from Roslin operator should be included in the `Run.output_metadata`. This will allow it to be used as the input for the Roslin QC pipeline, where it is needed to determine which database files to use for references

**Comment by stevekm** [comment]
working on that here: https://github.com/mskcc/beagle/pull/135

**Comment by allanbolipata** [comment]
We added this to the `roslin-cwl` pair workflow output so this shouldn't be needed for now.
