### ISSUE TITLE
Operator Chaining

### ISSUE THREAD

**Issue by sivkovic** [mskcc/beagle#127]
- Implement OperatorRun object which needs to contain
  - Links to the created Run objects
  - Chaining Type (1-1, Many-1)
  - Operator callback (List of operators which will be run after all runs are completed, or after each run is completed, based on the Chaining Type)
  - OperatorRun state

**Comment by allanbolipata** [comment]
@soccin This was completed in https://github.com/mskcc/beagle/pull/146; won't make checklist
