### ISSUE TITLE
Need to change references to `operator_job` to `create_jobs_from_request`

### ISSUE THREAD

**Issue by stevekm** [mskcc/beagle#130]
The current `operator_job` task used by [`OperatorViewSet`](https://github.com/mskcc/beagle/blob/ef722aae17dd8554ded53ad905a4d574d743d4e2/runner/views/run_api_view.py#L97) keeps crashing due to references to an unimported`warnings` module

https://github.com/mskcc/beagle/blob/ef722aae17dd8554ded53ad905a4d574d743d4e2/runner/tasks.py#L39

```
ERROR:celery.app.trace:Task runner.tasks.operator_job[638e4264-a53b-4dde-81c4-0d9c9031d32a] raised unexpected: NameError("name 'warnings' is not defined")
Traceback (most recent call last):
  File "/juno/work/ci/kellys5/projects/beagle-dev/beagle-dev5/conda/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/juno/work/ci/kellys5/projects/beagle-dev/beagle-dev5/runner/tasks.py", line 43, in operator_job
    warnings.warn("operator_job to be deprecated for create_jobs_from_request", DeprecationWarning, stacklevel=2)
NameError: name 'warnings' is not defined
```

This needs to be replaced with a reference to the new `create_jobs_from_request` instead.

**Comment by stevekm** [comment]
@aef- I think you might have fixed this?

**Comment by sivkovic** [comment]
@stevekm do you know is this fixed?

**Comment by allanbolipata** [comment]
I don't see it in `master` branch anymore so I believe this is fixed.

Closing.
