### ISSUE TITLE
Beagle jobs stuck at CREATING state if pipeline is unavailable

### ISSUE THREAD

**Issue by allanbolipata** [mskcc/beagle#137]
<img width="1366" alt="Screenshot 2020-02-14 at 03 53 18" src="https://user-images.githubusercontent.com/33229763/74516072-bcc53080-4edd-11ea-9471-c1e33b574c4b.png">

Three runs were stuck on CREATING state for hours in Beagle. This was because they were all trying to find a pipeline that was no longer available (it was deleted after they were merged in to another branch).

We will probably need to handle this case so it returns a more informative error to help debugging.

**Comment by nikhil** [comment]
As a note, it looks like this was before there were "OPERATOR_RUN" objects. I wonder if operator_runs have a similar issue of being stuck in a CREATING state
