### ISSUE TITLE
Usage of WSGI server + nginx for deployment

### ISSUE THREAD

**Issue by stevekm** [mskcc/beagle#138]
Standard practices for Django app deployment suggests using a WSGI server plus a web server like nginx or apache for production deployments;

https://docs.djangoproject.com/en/3.0/howto/deployment/

An example would be to use [`gunicorn`](https://docs.gunicorn.org/en/latest/install.html) + nginx;

https://docs.djangoproject.com/en/3.0/howto/deployment/wsgi/gunicorn/

and example of using this in production can be seen here:

https://github.com/NYU-Molecular-Pathology/IR-interpreter/blob/92663bc1e40c39c4f588a89cf2daaf0f02d4fa0c/Makefile#L101-L120

(nginx configuration and setup available as well)

This setup would solve the current problem of maintaining an active `manage.py runserver` process. `gunicorn` and nginx are able to run in 'daemon' mode. They can be easily managed by [tracking their process ID's](https://github.com/NYU-Molecular-Pathology/IR-interpreter/blob/92663bc1e40c39c4f588a89cf2daaf0f02d4fa0c/Makefile#L122-L127)

**Comment by stevekm** [comment]
example is set up for dmp2cmo here; `/juno/work/ci/server-conf/`

**Comment by sivkovic** [comment]
We should prioritize this since running in development server causing this error https://stackoverflow.com/questions/59651654/django-django-db-utils-operationalerror-fatal-remaining-connection-slots-are-r 
I think setting CONN_MAX_AGE wouldn't work for development server.
