### ISSUE TITLE
Move run creation logic from serializers into Run object

### ISSUE THREAD

**Issue by stevekm** [mskcc/beagle#144]
Right now, a lot of the logic for creating a new run appears to be implemented in [`CreateRunSerializer`](https://github.com/mskcc/beagle/blob/10af88a85dd7454462158f51887eaaf4e748ab56/runner/serializers.py#L36) and [APIRunCreateSerializer](https://github.com/mskcc/beagle/blob/10af88a85dd7454462158f51887eaaf4e748ab56/runner/serializers.py#L127). A [`Run` object class](https://github.com/mskcc/beagle/blob/develop/runner/run/objects/run_object.py#L8) already exists with various creation methods. I think it would be helpful to move all the "run creation" logic into the Run object so we dont have to use a serializer to create a run. This would reduce reduce fragmentation of these common functionalities across multiple unrelated  objects and make it more clear when & where we need to use serializers vs. just interact directly with `Run` and Run objects

**Comment by allanbolipata** [comment]
I don't think we're doing this, so closing. 

Re-open if needed.
