### ISSUE TITLE
Older jobs breaks admin page for beagle_etl

### ISSUE THREAD

**Issue by sivkovic** [mskcc/beagle#153]
Old jobs break admin for beagle_etl. Probably because some args are null.

http://silo:4001/admin/beagle_etl/job/?p=180

**Comment by aef-** [comment]
I may have fixed it with latest merge, let me know if it continues.

**Comment by stevekm** [comment]
I was having this as well and it seems to have went away after I deleted all my old Runs

**Comment by sivkovic** [comment]
Fixed in `1.1.0`:
https://github.com/mskcc/beagle/blob/release/1.1.0/beagle_etl/admin.py#L23
