### ISSUE TITLE
Need to be able to create a run from multiple Run ID's and request ID's

### ISSUE THREAD

**Issue by stevekm** [mskcc/beagle#157]
The current implementation of the creation of a run from a POST request only accepts the `request_ids` argument, and it creates one new run for each given `request_id`.

https://github.com/mskcc/beagle/blob/334ae4d736a72f42f94adf79b3366b3be5644662/runner/views/run_api_view.py#L94-L102

New Operators such as Roslin QC Operator need to be started with multiple Run ID's as a parameter. Also, it should be able to use a mixture of both Run ID's and request ID's as the starting parameter, so all of these need to create a single Operator Run with all of the provided Run ID's and request ID's as parameters, instead of creating a Run for each Run ID and request ID.

**Comment by sivkovic** [comment]
Implemented in `1.1.0`:
https://github.com/mskcc/beagle/blob/develop/runner/views/run_api_view.py#L94
