### ISSUE TITLE
Extend Beagle CLI with run commands

### ISSUE THREAD

**Issue by allanbolipata** [mskcc/beagle#17]
For run commands we should use 
`POST /v0/run/api/`
BODY:
{
    "app": <beagle_pipeline_id>,
    "inputs": <JSON>
}

File locations are specified as URIs (`bid://<beagle_file_uuid>` or `juno://<file_path>`)

We should also implement call:
`POST /v0/run/request/`
BODY:
{
  "request_ids": [
    "string"
  ],
  "pipeline_name": "string"
}

Pipeline name: ["tempo", "roslin"]

**Comment by stevekm** [comment]
added as part of this PR; https://github.com/mskcc/beagle_cli/pull/4
