### ISSUE TITLE
On ETL retry, only attempt retry on jobs that FAILED

### ISSUE THREAD

**Issue by allanbolipata** [mskcc/beagle#181]
Currently when we retry a job in the ETL, we do it for all jobs. We should instead do it so that it only retries on FAILED jobs.

This should mitigate our errors. This should also hypothetically fix our issue with trying to re-import a pooled normal that was imported by a previous request. @sivkovic Confirm if that is the case

**Comment by sivkovic** [comment]
This is implemented and it is in `1.1.0`.
https://github.com/mskcc/beagle/commit/accb16ce76f550c2bcf8a894e4c90dd4ceb518dd#diff-191c0d2a9703e726904588c2f3d99d60R11
