### ISSUE TITLE
Export three request IDs' DMP BAMs for testing

### ISSUE THREAD

**Issue by allanbolipata** [mskcc/beagle#194]
The following request ID and cmo Patient IDs will be used as test data sets for pairing
```
05816_CC C-59ADTL
09483_B C-JV34TP
10670 C-J6UKKJ
```
Export these to Voyager using the following File Group IDs.
```
9ace63bf-ed55-461c-9ac0-1c5ee710d957    # production

f62f5fb8-2dbd-45b2-8050-6dac56a4cc17   # staging
```

**Comment by stevekm** [comment]
59ADTL and J6UKKJ were imported to staging manually. JV34TP was not found in my databases.

**Comment by allanbolipata** [comment]
Will check if that's correct patient id

**Comment by allanbolipata** [comment]
This should be done.
