### ISSUE TITLE
Wrong log path for a failed job

### ISSUE THREAD

**Issue by nikhil** [mskcc/beagle#231]
The simple fix would be to use ci instead of pi. It would be better to get this path from Ridgeback to prevent this issue in the future.
https://github.com/mskcc/beagle/blob/9b293d09408573e661129782bff06fce808573c1/runner/tasks.py#L280

**Comment by nikhil** [comment]
https://github.com/mskcc/beagle/blob/develop/runner/tasks.py#L280

**Comment by allanbolipata** [comment]
Fixing #241 should make this obsolete
