### ISSUE TITLE
Add QC .pdf file to Jira

### ISSUE THREAD

**Issue by stevekm** [mskcc/beagle#232]
It looks like currently, the Roslin QC .pdf file is not getting uploaded to Jira, it should be added as a file on the Jira issue when complete. Thanks.

**Comment by allanbolipata** [comment]
I'm not sure we could do this right now.

The QC pdf is an output of the pipeline, whereas the other files were generated outside of the pipelines. Was this a requirement?

**Comment by allanbolipata** [comment]
Let's start with https://github.com/mskcc/roslin-cwl/blob/master/modules/project/generate-qc-sv.cwl#L105-L107 from the `RoslinQCOperator`

**Comment by allanbolipata** [comment]
Done in #260 #268
