### ISSUE TITLE
Request IDs for verifying runs

### ISSUE THREAD

**Issue by allanbolipata** [mskcc/beagle#267]
Here's a list of request IDs to run to verify proper pairing logic and chaining.

We have to be cognizant of storage space constraints.

```
09483_B
09483_G
09483_H
09483_J
09483_K
09483_M
09483_O
09483_P
09483_R
09483_S
09483_U
10226_F
10226_G
10226_H
10075_B
10075_D
```

**Comment by allanbolipata** [comment]
Some of these were running for tests already, but we want a fresh run for all of the requests/samples so that they can have a JIRA ticket associated with each of them.

So what I'm going to do:

1. Kill corresponding Voyager runs in staging
2. Delete all records for these requests in the staging DB
3. Re-import them, which kicks off a new JIRA ticket for each
4. Run them with ROSLIN-CWL

**Comment by nikhil** [comment]
Use this url as a base to track the requests: 
http://silo:4001/v0/run/api/?job_group=2ed31320-5396-4b25-9bef-57522ccb493b&job_group=016cc0c7-c8ea-456a-81b1-d91f955bc442&job_group=2cce3f3e-b125-486e-bbae-68972f4315e9&job_group=dd9e0e92-3d9a-4622-9387-04225e02482b&job_group=da1792f6-15f5-4794-aa13-95a7d56b6f86&job_group=fc8e40c7-216a-4aab-986d-dd9451d7e964&job_group=1ada5b68-5527-467e-8475-4f31556608d3&job_group=d5fb743d-7d1f-4b5c-908d-97d1133e5b68&job_group=c08b0300-0512-4f3c-ade3-bfc78bf91b83&job_group=90524ad0-f885-4d08-bd0a-26aa4953380e&job_group=29039f0b-ae3d-4c5a-90c3-a36d2d6fb54e&job_group=b461c911-be08-4a58-baa6-e2cb1635e1b2&job_group=2c217dca-7714-40d0-b5aa-e618fbe3f131&job_group=13e77301-d9c9-4b0f-acd6-4be8908eb320&job_group=8f3cc025-8d32-4e79-8dbe-18e93347c028&job_group=5331ba19-0f19-423f-8318-04c46f2eba44

**Comment by allanbolipata** [comment]
Jobs that went to CI review needed (sample fail import):
http://jira.mskcc.org:8090/projects/VADEV/issues/VADEV-171?filter=allopenissues
http://jira.mskcc.org:8090/projects/VADEV/issues/VADEV-172?filter=allopenissues
http://jira.mskcc.org:8090/projects/VADEV/issues/VADEV-174?filter=allopenissues

Find out which ones failed and give to CAS

CI Review Needed (TBD):
http://jira.mskcc.org:8090/projects/VADEV/issues/VADEV-182?filter=allopenissues
http://jira.mskcc.org:8090/projects/VADEV/issues/VADEV-177?filter=allopenissues
http://jira.mskcc.org:8090/projects/VADEV/issues/VADEV-180?filter=allopenissues

Find out why they went to that status

**Comment by nikhil** [comment]
For: http://jira.mskcc.org:8090/projects/VADEV/issues/VADEV-170?filter=allopenissues
It has failed due to a sample name `s_SK_MEL_645 E/670_2_CL_09483J`
> File is missing: file:///juno/work/ci/temp/work/811e97ed-bdc3-4651-ad05-652760eac7b9/toil-251cfb7d-26bc-4fe2-b7e6-e876d7f630ad-f37b4685-d5c5-4990-bdd1-e12bb62b7dc4/tmpv     rk4rgyg/59ba21e3-bb2c-4afd-809c-22c6236215d3/t6m0a5m58/tmp-outyakgam9p/s_SK_MEL_645%20E/670_2_CL_09483J.chunk000.sam

**Comment by allanbolipata** [comment]
http://jira.mskcc.org:8090/projects/VADEV/issues/VADEV-170?filter=allopenissues has failed due to a sample being named because sample was malformed (contains a space). - @nikhil

**Comment by allanbolipata** [comment]
http://jira.mskcc.org:8090/projects/VADEV/issues/VADEV-177?filter=allopenissues failed on helix filters during `concat.cwl`. @nikhil @stevekm

**Comment by allanbolipata** [comment]
Not entirely sure what's going on with http://jira.mskcc.org:8090/projects/VADEV/issues/VADEV-182?filter=allopenissues

This shows successful import and update of metadata:
http://silo:4001/admin/beagle_etl/job/?o=-6.-7&q=10075_D

The runs all look like the completed successfully. The only potential issue is duplicated rows in the sample mapping file - see #293 - but that shouldn't be switching the state to CI Review Needed.

**Comment by allanbolipata** [comment]
This is obsoleted!
