### ISSUE TITLE
Submit merge jobs to different JIRA board

### ISSUE THREAD

**Issue by allanbolipata** [mskcc/beagle#448]
Will need a way to submit to other JIRA boards besides VA

**Comment by allanbolipata** [comment]
Use RSL board for `merge` as a specs foundation

Two states -> Ready To Deliver and Done

Every time Voyager sees a new request for some study id, push to Ready To Deliver every time.

**Comment by allanbolipata** [comment]
@webbera Give this board a nice name

**Comment by webbera** [comment]
Project created. Name = VAMRG. There are 6 statuses:

- Open (initial status; all new issues start with the "Open" status; cannot transition back to "Open")
- Running Merge
- Failed Marge
- Ready to Deliver
- Done
- Won't Do

Each status can transition to each status, with the exception of the "Open" status.
