### ISSUE TITLE
allow mix of runModes while still separating machine types in Tempo runner

### ISSUE THREAD

**Issue by anoronh4** [mskcc/beagle#509]
Based on recent conversations with PM, IGO, CCS, and CSE teams, cmo samples are allowed to be analyzed with mixed runModes within Tempo, so long as they are the same machine type. For example we should be able to mix Novaseq S1 with Novaseq S2, but not Novaseq S1 with Hiseq High Output. 

Currently beagle just looks to make sure that there is one unique runMode. However, runMode should be modified or a new field can be made for machine type.  For example:
```
machineTypeMapping = {"Novaseq S1":"Novaseq","Novaseq S2":"Novaseq","Novaseq S4":"Novaseq", "HiSeq High Output":"HiSeq","HiSeq Rapid Run":"HiSeq"}
if runMode in machineTypeMapping:
  machineType = machineTypeMapping[runMode]
else:
  machineType = runMode
```
then instead of checking runMode, check machineType

**Comment by allanbolipata** [comment]
@anoronh4 Added in https://github.com/mskcc/beagle/commit/fdf595f21b503491592b5706259f6003caff62b7, this will be reflected in new runs

**Comment by allanbolipata** [comment]
Added in https://github.com/mskcc/beagle/pull/228
