### ISSUE TITLE
Add file-specific metadata, such as R1/R2 for fastqs, bam headers, etc., to File

### ISSUE THREAD

**Issue by allanbolipata** [mskcc/beagle#54]

**Comment by sivkovic** [comment]
Added R field with values R1 or R2 on import from LIMS

**Comment by stevekm** [comment]
I think this is related to https://github.com/mskcc/beagle/issues/85

some of the file-specific metadata we need overlaps with `Port.name` metadata that we also need to propagate to `File`/`FileMetadata` entries. 

maybe we could have a field on `FileMetadata` that allows for selection of choices such as `clstats1`, `clstats2`, `fastqR1`, `fastqR2`, etc..
