### ISSUE TITLE
Batch requests for status updates in Ridgeback

### ISSUE THREAD

**Issue by aef-** [mskcc/beagle#648]
If there are N running jobs, Beagle polls Ridgeback making N requests. We should just group the IDs and make a single request.

**Comment by sivkovic** [comment]
Batch call is a really good idea.
I would suggest adding batch on Ridgeback like:
Request:
```
{
    job_ids: [<job_id_1>, <job_id_2>, <job_id_3>]
}
```
Response:
```
{
  <job_id_1>: <job_body_1>,
  <job_id_2>: <job_body_2>,
  <job_id_3>: <job_body_3>,
}
```
And on Beagle side we can make something like
```GET /v0/runs/job-group/<job-group-1>/```

Which will make a batch call for all runs from that `job-group`.
