### ISSUE TITLE
exit code 120

### ISSUE THREAD

**Issue by ionox0** [mskcc/beagle#681]
http://voyager:5001/admin/runner/run/6be3f5ae-af53-426b-a73a-82b532ee4530/change/?_changelist_filters=app%3Da0dd19a3-2c55-462b-a09b-de0ac198cf43%26q%3D11442

Not a whole lot of information in the logs:
```
ju13 2021-01-21 15:10:30,803 Thread-113 ERROR toil.batchSystems.singleMachine: Got exit code 120 (indicating failure) from job _toil_worker CWLScatter file:/work/ci/beagle/job-store/034a698f-5a74-4561-824b-eac4c91f6647 kind-CWLScatter/instancepg8tgezg.
```

Possibly related to disk quota being exceeded, as seen in another failed job in same run:

http://voyager:5001/admin/runner/run/ffc4c03e-862f-4eba-9ea4-dbd1bd44cc90/change/?_changelist_filters=app%3Da0dd19a3-2c55-462b-a09b-de0ac198cf43%26q%3D11442

**Comment by allanbolipata** [comment]
We're definitely using up way more than we can clean up.

The new release of Ridgeback should mitigate these issues, but I will clear up some disk space for now.
