### ISSUE TITLE
Multiple workers running check_job_status

### ISSUE THREAD

**Issue by aef-** [mskcc/beagle#700]
This is related to the issue we're seeing where some `OperatorRuns` have the incorrect number of runs completed/failed -- typically way more than the number of runs associated. This bug prevents downstream pipelines from triggering.

[Voyager Example](http://voyager:5001/admin/runner/operatorrun/0d3bcb73-c829-46af-995a-ab4f27d9b857/change/)

[JIRA ticket](http://jira.mskcc.org:8090/browse/ACCESS-139?focusedCommentId=378022&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-378022)

What I'm seeing in the logs:
```
22342629:[2021-02-03 10:51:02,209: INFO/ForkPoolWorker-63] Checking status for job: b517adc1-fffe-433e-af02-1c704eae2340 [c8a6d7e5-4f2d-4572-9f53-e439c1895b21]
22342632:[2021-02-03 10:51:02,241: INFO/ForkPoolWorker-63] Job b517adc1-fffe-433e-af02-1c704eae2340 [c8a6d7e5-4f2d-4572-9f53-e439c1895b21] COMPLETED
22342634:[2021-02-03 10:51:02,422: INFO/ForkPoolWorker-64] Checking status for job: b517adc1-fffe-433e-af02-1c704eae2340 [c8a6d7e5-4f2d-4572-9f53-e439c1895b21]
22342636:[2021-02-03 10:51:02,447: INFO/ForkPoolWorker-64] Job b517adc1-fffe-433e-af02-1c704eae2340 [c8a6d7e5-4f2d-4572-9f53-e439c1895b21] COMPLETED
```
These are the same jobs completing twice, only milliseconds apart, from two different workers.

* Why does this appear to only affect `OperatorRuns` with >50 runs?
* Why doesn't this duplicate worker affect other jobs whose statuses also need to be checked and updated?

**Comment by aef-** [comment]
What I think is happening:

Every beat starts a new worker and each worker is created after 30 seconds. When we have jobs that require checking the status of 50+ runs, that worker can take more than 30 seconds causing a race condition between the two workers.

`ForkPoolWorker-63` and `ForkPoolWorker-64` will then check the statuses of a lot of the same runs, and when they find that one is completed, they'll both increment the `OperatorRun`

**Comment by ionox0** [comment]
🥳
