### ISSUE TITLE
'assay_coverage' for helix filters TMB input needs to come from assay type

### ISSUE THREAD

**Issue by stevekm** [mskcc/beagle#800]
Right now it appears that the value for `assay_coverage` is set to 10000000. It should instead be derived from the assay type, with this key;

```
{
    "IMPACT341": 896637,
    "IMPACT468": 1139294,
    "IMPACT410": 1016335,
    "IMPACT505": 1213770
}
```

**Comment by allanbolipata** [comment]
@stevekm I believe this is corrected as it was already in the operator - the keys were different than expected so the values weren't being loaded. 

Closing.
