### ISSUE TITLE
Normal samples remain unpaired in tempo-mpgen even when tumor available.

### ISSUE THREAD

**Issue by anoronh4** [mskcc/beagle#853]
We have the following samples:
```
$ grep s_C_000696_ /juno/work/tempo/voyager/sample_unpaired.txt  | grep 07566_E
s_C_000696_M001_d	C-000696	07566_E_14	Resection	NovaSeq S2	Unknown Tumor	Agilent_v4_51MB_Human_hg19_BAITS	2018-02-22	No normals for patient
s_C_000696_N001_d	C-000696	07566_E_13	Blood	NovaSeq S2	Unknown Tumor	Agilent_v4_51MB_Human_hg19_BAITS	2018-02-22	No normals for patient
```
Looks to me like it should have enough info to pair. The `sampleClass` says `Unknown Tumor` but the `tumorOrNormal` field in the voyager database has them classified as `Normal` and `Tumor`. Is the `sampleClass` overriding  the `tumorOrNormal` field somewhere that I am not seeing?

**Comment by allanbolipata** [comment]
For this one, guidance has been that `sampleClass` supercedes `tumorOrNormal`, as `tumorOrNormal` is considered less stable.

If `s_C_000696_N001_d` is a normal, as we discussed we'll need to verify with the PMs. I will close for now.
