### ISSUE TITLE
Create Roslin QC operator

### ISSUE THREAD

**Issue by allanbolipata** [mskcc/beagle#86]
- [x] Create CWL that will be used for QC
- [x] Prototype successful run of QC with test input data
- [x] From prototype, implement QC operator and add it to Beagle #182

**Comment by allanbolipata** [comment]
Currently being worked on by @stevekm here: https://github.com/mskcc/beagle/tree/roslin-qc

**Comment by stevekm** [comment]
waiting on updates from here required for full implementation: https://github.com/mskcc/beagle/pull/135

in the mean time, accomplish this by using the saved JSON data instead.
