### ISSUE TITLE
Create a Port File table

### ISSUE THREAD

**Issue by nikhil** [mskcc/beagle#97]
Create a new Model which will create a connection between File objects and Ports.

**Comment by stevekm** [comment]
Do we know if this should be a simple ForeignKey relationship, or a ManyToMany relationship? 

Here is example for ManyToMany; 
https://docs.djangoproject.com/en/3.0/topics/db/models/#many-to-many-relationships
https://gist.github.com/jhgaylor/5873301

usage discussion: 
https://www.revsys.com/tidbits/tips-using-djangos-manytomanyfield/

if it is indeed a ManyToMany relationship, then I think we can just add something like this to the [model](https://github.com/mskcc/beagle/blob/f4f019970af75c48385d79b8c750e0f35890d6df/runner/models.py#L49);

```
class Port(BaseModel):
    files = models.ManyToManyField(File)
```

@allanbolipata @sivkovic
